- [Google Charts](https://developers.google.com/chart/interactive/docs)
- [data source: National Bureau of Statistics of China](https://data.stats.gov.cn/english/easyquery.htm?cn=E0103)

> you may need to install xlrd package
```
pip install xlrd
```

In [1]:
import pandas as pd
import numpy as np

In [14]:
# load GDP Data 
# change to Billion by / 10
gdp = pd.read_excel("data/AnnualbyProvince-gdp.xls", skiprows=3, nrows=31, index_col=0)
gdp = (gdp / 10).round(2)
gdp.head()

,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013
Region,,,,,,,,,,
Beijing,4161.10,4104.56,3594.33,3544.51,3310.60,2988.30,2704.12,2477.91,2292.60,2113.46
Tianjin,1631.13,1568.51,1400.80,1405.55,1336.29,1245.06,1147.72,1087.95,1064.06,994.54
Hebei,4237.04,4039.71,3601.38,3497.86,3249.46,3064.08,2847.41,2639.84,2520.89,2425.96
Shanxi,2564.26,2287.04,1783.56,1696.16,1595.81,1448.43,1194.64,1183.64,1209.47,1198.72
Inner Mongolia,2315.87,2116.60,1725.80,1721.25,1614.08,1489.81,1378.93,1294.90,1215.82,1139.24

# Google Bar Chart

In [18]:
df = gdp["2022"].sort_values(ascending=False).reset_index()
df['annotation'] = df['2022'].apply(lambda x: f"{x:,.0f}")
df.values

array([['Guangdong', 12911.86, '12,912'],
       ['Jiangsu', 12287.56, '12,288'],
       ['Shandong', 8743.51, '8,744'],
       ['Zhejiang', 7771.54, '7,772'],
       ['Henan', 6134.51, '6,135'],
       ['Sichuan', 5674.98, '5,675'],
       ['Hubei', 5373.49, '5,373'],
       ['Fujian', 5310.99, '5,311'],
       ['Hunan', 4867.04, '4,867'],
       ['Anhui', 4504.5, '4,504'],
       ['Shanghai', 4465.28, '4,465'],
       ['Hebei', 4237.04, '4,237'],
       ['Beijing', 4161.1, '4,161'],
       ['Shaanxi', 3277.27, '3,277'],
       ['Jiangxi', 3207.47, '3,207'],
       ['Chongqing', 2912.9, '2,913'],
       ['Liaoning', 2897.51, '2,898'],
       ['Yunnan', 2895.42, '2,895'],
       ['Guangxi', 2630.09, '2,630'],
       ['Shanxi', 2564.26, '2,564'],
       ['Inner Mongolia', 2315.87, '2,316'],
       ['Guizhou', 2016.46, '2,016'],
       ['Xinjiang', 1774.13, '1,774'],
       ['Tianjin', 1631.13, '1,631'],
       ['Heilongjiang', 1590.1, '1,590'],
       ['Jilin', 1307.02, '1,307'],
       ['Gansu', 1120.16, '1,120'],
       ['Hainan', 681.82, '682'],
       ['Ningxia', 506.96, '507'],
       ['Qinghai', 361.01, '361'],
       ['Tibet', 213.26, '213']], dtype=object)

# Line Chart

In [52]:
# load GDP Data 
# change to Billion by / 10
gdp = pd.read_excel("data/Annual_20years.xls", skiprows=2, nrows=1, index_col=0)
gdp = (gdp / 10).round(2)
gdp.head()

,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003
Indicators,,,,,,,,,,,,,,,,,,,,
Gross National Income(100 million yuan),119721.5,113880.71,100545.13,98375.12,91524.35,83094.57,74269.41,68557.12,64438.02,58814.12,53732.9,48339.28,41035.41,34793.49,32122.95,27070.4,21902.85,18599.89,16141.54,13657.63

In [54]:
gdp.T.reset_index().sort_values('index').values

array([['2003', 13657.63],
       ['2004', 16141.54],
       ['2005', 18599.89],
       ['2006', 21902.85],
       ['2007', 27070.4],
       ['2008', 32122.95],
       ['2009', 34793.49],
       ['2010', 41035.41],
       ['2011', 48339.28],
       ['2012', 53732.9],
       ['2013', 58814.12],
       ['2014', 64438.02],
       ['2015', 68557.12],
       ['2016', 74269.41],
       ['2017', 83094.57],
       ['2018', 91524.35],
       ['2019', 98375.12],
       ['2020', 100545.13],
       ['2021', 113880.71],
       ['2022', 119721.5]], dtype=object)

# Treemap Chart

In [60]:
# load GDP Data 
# change to Billion by / 10
gdp = pd.read_excel("data/AnnualbyProvince-gdp.xls", skiprows=3, nrows=31, index_col=0)
gdp = (gdp / 10).round(2)[["2022"]]
gdp['Parent'] = 'China'
gdp['size'] = gdp['2022']
gdp.reset_index()[['Region', 'Parent', '2022', 'size']].values

array([['Beijing', 'China', 4161.1, 4161.1],
       ['Tianjin', 'China', 1631.13, 1631.13],
       ['Hebei', 'China', 4237.04, 4237.04],
       ['Shanxi', 'China', 2564.26, 2564.26],
       ['Inner Mongolia', 'China', 2315.87, 2315.87],
       ['Liaoning', 'China', 2897.51, 2897.51],
       ['Jilin', 'China', 1307.02, 1307.02],
       ['Heilongjiang', 'China', 1590.1, 1590.1],
       ['Shanghai', 'China', 4465.28, 4465.28],
       ['Jiangsu', 'China', 12287.56, 12287.56],
       ['Zhejiang', 'China', 7771.54, 7771.54],
       ['Anhui', 'China', 4504.5, 4504.5],
       ['Fujian', 'China', 5310.99, 5310.99],
       ['Jiangxi', 'China', 3207.47, 3207.47],
       ['Shandong', 'China', 8743.51, 8743.51],
       ['Henan', 'China', 6134.51, 6134.51],
       ['Hubei', 'China', 5373.49, 5373.49],
       ['Hunan', 'China', 4867.04, 4867.04],
       ['Guangdong', 'China', 12911.86, 12911.86],
       ['Guangxi', 'China', 2630.09, 2630.09],
       ['Hainan', 'China', 681.82, 681.82],
       ['Chongqing', 'China', 2912.9, 2912.9],
       ['Sichuan', 'China', 5674.98, 5674.98],
       ['Guizhou', 'China', 2016.46, 2016.46],
       ['Yunnan', 'China', 2895.42, 2895.42],
       ['Tibet', 'China', 213.26, 213.26],
       ['Shaanxi', 'China', 3277.27, 3277.27],
       ['Gansu', 'China', 1120.16, 1120.16],
       ['Qinghai', 'China', 361.01, 361.01],
       ['Ningxia', 'China', 506.96, 506.96],
       ['Xinjiang', 'China', 1774.13, 1774.13]], dtype=object)

# Bubble Chart

In [112]:
life = pd.read_excel("data/AnnualbyProvince-life.xls", skiprows=3, nrows=31, index_col=0)
life.columns  = ['life']
population = pd.read_excel("data/AnnualbyProvince-population.xls", skiprows=3, nrows=31, index_col=0)
population.columns  = ['population']
rate = pd.read_excel("data/AnnualbyProvince-birthrate.xls", skiprows=3, nrows=31, index_col=0)
rate.columns  = ['birth_rate']
df = pd.concat([rate, population, life], axis=1)
df['parent'] = 'China'
df.reset_index()[['Region', 'life', 'birth_rate', 'parent', 'population']].values

array([['Beijing', 80.18, 7.48, 'China', 1962],
       ['Tianjin', 78.89, 8.18, 'China', 1299],
       ['Hebei', 74.97, 13.22, 'China', 7194],
       ['Shanxi', 74.92, 10.68, 'China', 3574],
       ['Inner Mongolia', 74.44, 9.3, 'China', 2472],
       ['Liaoning', 76.38, 6.68, 'China', 4375],
       ['Jilin', 76.18, 7.91, 'China', 2747],
       ['Heilongjiang', 75.98, 7.35, 'China', 3833],
       ['Shanghai', 80.26, 7.05, 'China', 2303],
       ['Jiangsu', 76.63, 9.73, 'China', 7869],
       ['Zhejiang', 77.73, 10.27, 'China', 5447],
       ['Anhui', 75.08, 12.7, 'China', 5957],
       ['Fujian', 75.76, 11.27, 'China', 3693],
       ['Jiangxi', 74.33, 13.72, 'China', 4462],
       ['Shandong', 76.46, 11.65, 'China', 9588],
       ['Henan', 74.57, 11.52, 'China', 9405],
       ['Hubei', 74.87, 10.36, 'China', 5728],
       ['Hunan', 74.7, 13.1, 'China', 6570],
       ['Guangdong', 76.49, 11.18, 'China', 10441],
       ['Guangxi', 75.11, 14.13, 'China', 4610],
       ['Hainan', 76.3, 14.71, 'China', 869],
       ['Chongqing', 75.7, 9.17, 'China', 2885],
       ['Sichuan', 74.75, 8.93, 'China', 8045],
       ['Guizhou', 71.1, 13.96, 'China', 3479],
       ['Yunnan', 69.54, 13.1, 'China', 4602],
       ['Tibet', 68.17, 15.8, 'China', 300],
       ['Shaanxi', 74.68, 9.73, 'China', 3735],
       ['Gansu', 72.23, 12.05, 'China', 2560],
       ['Qinghai', 69.96, 14.94, 'China', 563],
       ['Ningxia', 73.38, 14.14, 'China', 633],
       ['Xinjiang', 72.35, 15.99, 'China', 2185]], dtype=object)